language: minimal
sudo: required
branches:
  only:
  - master
services:
  - docker
before_script:
  - 'docker -v'
  - 'export IMAGE_TAG=$(date +%s)'
  - 'export IMAGE_NAME=francescotonini/univrorari-backend'
script:
  - 'docker build --force-rm=true --no-cache -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .'
after_script:
  - 'docker images'
before_deploy:
  - 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
deploy:
  - 'docker push $IMAGE_NAME:$IMAGE_TAG'
  - 'docker push $IMAGE_NAME:latest'